name: Push master to release branch after a new GitHub release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@example.com"

      - name: Merge and Push
        run: |
          git fetch origin release:release || echo "No release branch yet"
          git checkout release || git checkout -b release
          git merge --no-edit origin/master
          git push origin release
